export const error_code = {
  ERROR_CODE_INVALID_USERNAME: '001',
  ERROR_CODE_INVALID_PASSWORD: '002',

  ERROR_CODE_EMAIL_EXISTS: '003',
  ERROR_CODE_PHONE_EXISTS: '004',

  ERROR_CODE_UNAUTHORIZED: '005',
};
